In [24]:
import os
from pathlib import Path

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.style

Đọc dữ liệu đầu vào từ file csv

In [4]:
data_dir = Path(r"D:\AWS\Datasets\Marketing & E-Commerce Analytics Dataset")

# Chọn đúng ba file cần thiết
required_files = ['events.csv', 'products.csv', 'transactions.csv']
selected_files = [data_dir / fname for fname in required_files]

# Kiểm tra file tồn tại
missing_files = [f for f in selected_files if not f.exists()]
if missing_files:
    raise FileNotFoundError(f'Missing required CSV files: {missing_files}')

print('Các file CSV được chọn:')
for f in selected_files:
    print('-', f.name)

# Đọc từng file riêng lẻ
data_frames = {f.name: pd.read_csv(f) for f in selected_files}
for name, df in data_frames.items():
    print(f"{name}: {df.shape} rows, {df.shape[1]} columns")

Các file CSV được chọn:
- events.csv
- products.csv
- transactions.csv
events.csv: (2000000, 12) rows, 12 columns
products.csv: (2000, 6) rows, 6 columns
transactions.csv: (103127, 9) rows, 9 columns

Xem xét dữ liệu ban đầu

In [32]:
for name, df in data_frames.items():
    print(f"--- {name} ---")
    display(df.head(20))
    print()

--- events.csv ---

,event_id,timestamp,customer_id,session_id,event_type,product_id,device_type,traffic_source,campaign_id,page_category,session_duration_sec,experiment_group
0,1,2021-01-14 13:35:43,43812,535101,view,1004.0,desktop,Email,43,PLP,115.1,Control
1,2,2021-12-03 21:36:50,71340,96426,add_to_cart,986.0,desktop,Email,10,PDP,32.4,Variant_A
2,3,2021-12-27 08:25:15,59540,220126,purchase,1630.0,mobile,Organic,0,PDP,190.7,Variant_A
3,4,2022-01-22 15:06:54,3601,484555,add_to_cart,1532.0,desktop,Paid Search,30,Checkout,134.8,Variant_B
4,5,2021-05-10 12:03:09,92735,60646,bounce,NaN,desktop,Email,26,PLP,53.1,Variant_A
5,6,2022-03-04 11:41:45,3184,221551,click,628.0,desktop,Organic,0,PDP,36.8,Variant_A
6,7,2021-01-27 10:17:26,89606,569910,click,369.0,desktop,Organic,0,PDP,58.2,Variant_B
7,8,2023-07-29 00:49:05,59581,184066,view,713.0,mobile,Social,8,PDP,153.1,Control
8,9,2023-06-06 21:14:26,54871,179212,purchase,1901.0,mobile,Paid Search,21,PLP,121.1,Control
9,10,2023-05-30 05:56:14,55257,240165,add_to_cart,755.0,mobile,Direct,0,PLP,73.3,Control
10,11,2021-09-06 21:26:22,94678,294260,add_to_cart,1141.0,mobile,Organic,0,Home,12.8,Variant_B
11,12,2023-08-24 04:44:17,86107,176767,view,1173.0,mobile,Email,7,PDP,26.4,Variant_A
12,13,2023-08-16 01:32:45,16251,367937,view,1873.0,tablet,Social,48,PLP,203.6,Control
13,14,2021-01-18 19:38:24,28041,388445,click,1188.0,desktop,Social,9,PDP,178.8,Control
14,15,2022-09-10 07:05:51,8024,292502,bounce,NaN,desktop,Organic,0,Checkout,33.0,Variant_B
15,16,2023-07-16 20:33:23,30501,36337,view,1337.0,mobile,Direct,0,Cart,297.9,Control
16,17,2021-04-14 13:12:42,47785,438870,add_to_cart,748.0,mobile,Organic,0,Checkout,52.4,Control
17,18,2022-09-29 17:11:49,76682,623341,add_to_cart,1672.0,mobile,Social,31,PDP,21.0,Variant_A
18,19,2021-10-04 19:02:42,81842,249671,view,618.0,desktop,Organic,0,Cart,227.7,Control
19,20,2023-11-30 19:08:16,69864,54913,view,1822.0,desktop,Direct,0,PLP,177.6,Control

--- products.csv ---

    product_id     category     brand  base_price launch_date  is_premium
0            1      Grocery  Brand_58       14.19  2021-08-02           0
1            2      Fashion   Brand_1       25.80  2021-09-14           0
2            3  Electronics  Brand_70      165.46  2021-01-18           1
3            4      Fashion  Brand_56       75.45  2023-03-03           1
4            5       Sports   Brand_1       72.50  2022-04-19           1
5            6      Fashion  Brand_39       57.08  2023-09-16           0
6            7       Beauty  Brand_42       27.23  2023-05-17           0
7            8         Home  Brand_41      121.82  2021-02-16           1
8            9         Home  Brand_73       25.37  2023-03-11           0
9           10         Home  Brand_61       84.11  2022-08-21           1
10          11       Sports   Brand_8       77.71  2022-04-20           1
11          12      Fashion  Brand_20       14.74  2021-07-27           0
12          13         Home  Brand_39       61.81  2022-06-15           1
13          14         Home  Brand_57       73.61  2023-05-02           1
14          15       Sports  Brand_88      100.75  2022-11-13           1
15          16      Grocery  Brand_28       15.92  2021-12-18           0
16          17  Electronics  Brand_75      146.18  2022-08-27           1
17          18       Sports  Brand_49       72.39  2022-05-08           1
18          19       Sports  Brand_81      128.05  2022-03-23           1
19          20         Home  Brand_16      123.17  2022-12-11           1

--- transactions.csv ---

,transaction_id,timestamp,customer_id,product_id,quantity,discount_applied,gross_revenue,campaign_id,refund_flag
0,1,2021-12-27 08:25:15,59540,1630.0,3,0.00,43.74,0,0
1,2,2023-06-06 21:14:26,54871,1901.0,3,0.00,174.78,21,0
2,3,2023-08-31 05:29:54,51818,1884.0,1,0.00,40.61,37,0
3,4,2022-06-26 20:33:46,18164,1114.0,2,0.15,68.76,13,0
4,5,2023-07-26 18:12:35,86915,408.0,1,0.00,14.64,4,0
5,6,2023-01-19 14:05:58,10749,1635.0,2,0.00,169.74,13,0
6,7,2023-07-28 09:37:53,25984,244.0,2,0.00,42.48,21,0
7,8,2022-07-10 07:29:15,85140,1296.0,1,0.00,36.95,2,0
8,9,2023-11-02 05:22:44,52930,1512.0,1,0.00,125.59,23,0
9,10,2021-01-25 06:28:42,69172,1433.0,1,0.15,48.72,44,0
10,11,2022-06-27 07:48:48,13992,154.0,2,0.00,94.70,13,0
11,12,2021-04-04 21:06:51,69122,781.0,1,0.20,-97.41,30,1
12,13,2023-03-09 15:36:33,45997,1513.0,1,0.00,100.76,43,0
13,14,2022-05-03 20:41:13,4344,1167.0,1,0.00,17.92,0,0
14,15,2021-07-27 16:22:47,30203,1099.0,1,0.00,123.87,46,0
15,16,2021-02-13 07:36:17,33154,NaN,1,0.05,NaN,29,0
16,17,2023-08-27 12:23:10,25737,1210.0,2,0.10,69.57,44,0
17,18,2023-03-30 16:42:58,75725,785.0,1,0.00,138.25,19,0
18,19,2021-07-26 14:10:11,11918,1960.0,1,0.00,251.08,19,0
19,20,2023-07-31 13:11:49,30583,899.0,1,0.00,-176.65,4,1

In [ ]:
for name, df in data_frames.items():
    print(f"--- {name} info ---")
    df.info()
    print()

--- events.csv info ---
<class 'pandas.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Data columns (total 12 columns):
 #   Column                Dtype
---  ------                -----
 0   event_id              int64
 1   timestamp             str
 2   customer_id           int64
 3   session_id            int64
 4   event_type            str
 5   product_id            float64
 6   device_type           str
 7   traffic_source        str
 8   campaign_id           int64
 9   page_category         str
 10  session_duration_sec  float64
 11  experiment_group      str
dtypes: float64(2), int64(4), str(6)
memory usage: 183.1 MB

--- products.csv info ---
<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   product_id   2000 non-null   int64
 1   category     2000 non-null   str
 2   brand        2000 non-null   str
 3   base_price   2000 non-null   float64
 4   launch_date  2000 non-null   str
 5   is_premium   2000 non-null   int64
dtypes: float64(1), int64(2), str(3)
memory usage: 93.9 KB

--- transactions.csv info ---
<class 'pandas.DataFrame'>
RangeIndex: 103127 entries, 0 to 103126
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    103127 non-null  int64
 1   timestamp         103127 non-null  str
 2   customer_id       103127 non-null  int64
 3   product_id        92678 non-null   float64
 4   quantity          103127 non-null  int64
 5   discount_applied  103127 non-null  float64
 6   gross_revenue     92678 non-null   float64
 7   campaign_id       103127 non-null  int64
 8   refund_flag       103127 non-null  int64
dtypes: float64(3), int64(5), str(1)
memory usage: 7.1 MB

Thống kê các chỉ số định lượng trên dữ liệu hiện tại

In [26]:
for name, df in data_frames.items():
    print(f"--- Thống kê {name} ---")
    display(df.describe(include='all'))
    print()

--- Thống kê events.csv ---

,event_id,timestamp,customer_id,session_id,event_type,product_id,device_type,traffic_source,campaign_id,page_category,session_duration_sec,experiment_group
count,2.000000e+06,2000000,2.000000e+06,2.000000e+06,2000000,1.799629e+06,1959700,2000000,2.000000e+06,2000000,2.000000e+06,2000000
unique,NaN,1977065,NaN,NaN,5,NaN,3,10,NaN,5,NaN,3
top,NaN,2023-09-18 07:00:22,NaN,NaN,view,NaN,mobile,Organic,NaN,PLP,NaN,Control
freq,NaN,4,NaN,NaN,1043573,NaN,1176146,776758,NaN,601284,NaN,1198404
mean,1.000000e+06,NaN,5.001209e+04,3.330514e+05,NaN,1.000100e+03,NaN,NaN,1.276203e+01,NaN,1.306426e+02,NaN
std,5.773504e+05,NaN,2.887960e+04,1.924715e+05,NaN,5.776716e+02,NaN,NaN,1.634052e+01,NaN,1.590376e+02,NaN
min,1.000000e+00,NaN,1.000000e+00,1.000000e+00,NaN,1.000000e+00,NaN,NaN,0.000000e+00,NaN,1.000000e-01,NaN
25%,5.000008e+05,NaN,2.501000e+04,1.662308e+05,NaN,5.000000e+02,NaN,NaN,0.000000e+00,NaN,5.810000e+01,NaN
50%,1.000000e+06,NaN,5.000900e+04,3.328190e+05,NaN,1.000000e+03,NaN,NaN,0.000000e+00,NaN,1.017000e+02,NaN
75%,1.500000e+06,NaN,7.503800e+04,4.997712e+05,NaN,1.501000e+03,NaN,NaN,2.600000e+01,NaN,1.640000e+02,NaN
max,2.000000e+06,NaN,1.000000e+05,6.666660e+05,NaN,2.000000e+03,NaN,NaN,5.000000e+01,NaN,7.533800e+03,NaN

--- Thống kê products.csv ---

,product_id,category,brand,base_price,launch_date,is_premium
count,2000.000000,2000,2000,2000.000000,2000,2000.000000
unique,NaN,6,100,NaN,901,NaN
top,NaN,Electronics,Brand_7,NaN,2021-01-18,NaN
freq,NaN,455,32,NaN,7,NaN
mean,1000.500000,NaN,NaN,72.166650,NaN,0.500000
std,577.494589,NaN,NaN,52.315792,NaN,0.500125
min,1.000000,NaN,NaN,5.110000,NaN,0.000000
25%,500.750000,NaN,NaN,32.505000,NaN,0.000000
50%,1000.500000,NaN,NaN,61.245000,NaN,0.500000
75%,1500.250000,NaN,NaN,97.955000,NaN,1.000000
max,2000.000000,NaN,NaN,464.580000,NaN,1.000000

--- Thống kê transactions.csv ---

,transaction_id,timestamp,customer_id,product_id,quantity,discount_applied,gross_revenue,campaign_id,refund_flag
count,103127.000000,103127,103127.000000,92678.00000,103127.000000,103127.000000,92678.000000,103127.000000,103127.000000
unique,NaN,103074,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,2022-11-06 18:59:39,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,51564.000000,NaN,49946.662707,999.63139,1.381539,0.041379,90.355493,19.945252,0.029372
std,29770.344943,NaN,28841.644812,576.19187,0.748176,0.060286,100.684683,16.379672,0.168846
min,1.000000,NaN,2.000000,1.00000,1.000000,0.000000,-783.040000,0.000000,0.000000
25%,25782.500000,NaN,25081.000000,498.00000,1.000000,0.000000,34.240000,4.000000,0.000000
50%,51564.000000,NaN,49957.000000,1002.00000,1.000000,0.000000,68.000000,18.000000,0.000000
75%,77345.500000,NaN,74870.500000,1498.00000,1.000000,0.050000,117.617500,34.000000,0.000000
max,103127.000000,NaN,100000.000000,2000.00000,4.000000,0.200000,1858.320000,50.000000,1.000000

Kiểm tra dữ liệu bị thiếu, dữ liệu bị trùng

In [27]:
for name, df in data_frames.items():
    print(f"--- Kiểm tra {name} ---")
    print('Số lượng dòng bị trùng trong tập dữ liệu:', df.duplicated().sum())
    print('Số lượng giá trị bị thiếu trong toàn bộ DataFrame:', df.isna().sum().sum())
    print('Số lượng giá trị thiếu (NaN) theo cột:')
    print(df.isna().sum())
    print()

--- Kiểm tra events.csv ---
Số lượng dòng bị trùng trong tập dữ liệu: 0
Số lượng giá trị bị thiếu trong toàn bộ DataFrame: 240671
Số lượng giá trị thiếu (NaN) theo cột:
event_id                     0
timestamp                    0
customer_id                  0
session_id                   0
event_type                   0
product_id              200371
device_type              40300
traffic_source               0
campaign_id                  0
page_category                0
session_duration_sec         0
experiment_group             0
dtype: int64

--- Kiểm tra products.csv ---
Số lượng dòng bị trùng trong tập dữ liệu: 0
Số lượng giá trị bị thiếu trong toàn bộ DataFrame: 0
Số lượng giá trị thiếu (NaN) theo cột:
product_id     0
category       0
brand          0
base_price     0
launch_date    0
is_premium     0
dtype: int64

--- Kiểm tra transactions.csv ---
Số lượng dòng bị trùng trong tập dữ liệu: 0
Số lượng giá trị bị thiếu trong toàn bộ DataFrame: 20898
Số lượng giá trị thiếu (NaN) theo cột:
transaction_id          0
timestamp               0
customer_id             0
product_id          10449
quantity                0
discount_applied        0
gross_revenue       10449
campaign_id             0
refund_flag             0
dtype: int64

In [28]:
for name, df in data_frames.items():
     print(f"{name} missing values:")
     display(df.isna().sum().to_frame('missing_count'))

events.csv missing values:

                      missing_count
event_id                          0
timestamp                         0
customer_id                       0
session_id                        0
event_type                        0
product_id                   200371
device_type                   40300
traffic_source                    0
campaign_id                       0
page_category                     0
session_duration_sec              0
experiment_group                  0

products.csv missing values:

             missing_count
product_id               0
category                 0
brand                    0
base_price               0
launch_date              0
is_premium               0

transactions.csv missing values:

                  missing_count
transaction_id                0
timestamp                     0
customer_id                   0
product_id                10449
quantity                      0
discount_applied              0
gross_revenue             10449
campaign_id                   0
refund_flag                   0

In [29]:
# Đọc các giá trị duy nhất của cột 'event_type', device_type, traffic_source, page_category, experiment_group trong events.csv
events_df = data_frames['events.csv']
unique_event_types = events_df['event_type'].unique()
unique_device_types = events_df['device_type'].unique()
unique_traffic_sources = events_df['traffic_source'].unique()
unique_page_categories = events_df['page_category'].unique()
unique_experiment_groups = events_df['experiment_group'].unique()
print("'event_type':", unique_event_types)
print("'device_type':", unique_device_types)
print("'traffic_source':", unique_traffic_sources)
print("'page_category':", unique_page_categories)
print("'experiment_group':", unique_experiment_groups)



# Đếm số lượng mỗi loại event_type, device_type, traffic_source, page_category, experiment_group trong events.csv
event_type_counts = events_df['event_type'].value_counts()
device_type_counts = events_df['device_type'].value_counts()
traffic_source_counts = events_df['traffic_source'].value_counts()
page_category_counts = events_df['page_category'].value_counts()
experiment_group_counts = events_df['experiment_group'].value_counts()

print("Số lượng mỗi loại 'event_type':")
print(event_type_counts)
print("Số lượng mỗi loại 'device_type':")
print(device_type_counts)
print("Số lượng mỗi loại 'traffic_source':")
print(traffic_source_counts)
print("Số lượng mỗi loại 'page_category':")
print(page_category_counts)
print("Số lượng mỗi loại 'experiment_group':")
print(experiment_group_counts)

'event_type': <StringArray>
['view', 'add_to_cart', 'purchase', 'bounce', 'click']
Length: 5, dtype: str
'device_type': <StringArray>
['desktop', 'mobile', 'tablet', nan]
Length: 4, dtype: str
'traffic_source': <StringArray>
[      'Email',     'Organic', 'Paid Search',      'Social',      'Direct',
 'PAID SEARCH',      'DIRECT',       'EMAIL',     'ORGANIC',      'SOCIAL']
Length: 10, dtype: str
'page_category': <StringArray>
['PLP', 'PDP', 'Checkout', 'Home', 'Cart']
Length: 5, dtype: str
'experiment_group': <StringArray>
['Control', 'Variant_A', 'Variant_B']
Length: 3, dtype: str
Số lượng mỗi loại 'event_type':
event_type
view           1043573
click           379008
add_to_cart     284370
bounce          189922
purchase        103127
Name: count, dtype: int64
Số lượng mỗi loại 'device_type':
device_type
mobile     1176146
desktop     685433
tablet       98121
Name: count, dtype: int64
Số lượng mỗi loại 'traffic_source':
traffic_source
Organic        776758
Paid Search    387657
Social         291194
Email          290651
Direct         193870
ORGANIC         23731
PAID SEARCH     12181
SOCIAL           9077
EMAIL            8989
DIRECT           5892
Name: count, dtype: int64
Số lượng mỗi loại 'page_category':
page_category
PLP         601284
PDP         599638
Home        399723
Checkout    199871
Cart        199484
Name: count, dtype: int64
Số lượng mỗi loại 'experiment_group':
experiment_group
Control      1198404
Variant_A     401413
Variant_B     400183
Name: count, dtype: int64

In [30]:
# Đọc các giá trị duy nhất của cột category trong products.csv
products_df = data_frames['products.csv']
unique_categories = products_df['category'].unique()
print("'category':", unique_categories)

# Đếm số lượng mỗi loại category trong products.csv
category_counts = products_df['category'].value_counts()
print("Số lượng mỗi loại 'category':")
print(category_counts)

'category': <StringArray>
['Grocery', 'Fashion', 'Electronics', 'Sports', 'Beauty', 'Home']
Length: 6, dtype: str
Số lượng mỗi loại 'category':
category
Electronics    455
Fashion        418
Home           396
Grocery        312
Sports         218
Beauty         201
Name: count, dtype: int64

In [31]:
# đọc các giá trị duy nhất của cột quantity, discount_applied, refund_flag trong transactions.csv
transactions_df = data_frames['transactions.csv']
unique_quantities = transactions_df['quantity'].unique()
unique_discounts = transactions_df['discount_applied'].unique()
unique_refunds = transactions_df['refund_flag'].unique()
print("'quantity':", unique_quantities)
print("'discount_applied':", unique_discounts)
print("'refund_flag':", unique_refunds)

# đếm số lượng mỗi loại quantity, discount_applied, refund_flag trong transactions.csv
quantity_counts = transactions_df['quantity'].value_counts()
discount_counts = transactions_df['discount_applied'].value_counts()
refund_counts = transactions_df['refund_flag'].value_counts()
print("Số lượng mỗi loại 'quantity':")
print(quantity_counts)
print("Số lượng mỗi loại 'discount_applied':")
print(discount_counts)
print("Số lượng mỗi loại 'refund_flag':")
print(refund_counts)

# đếm số lượng gross_revenue bị âm trong transactions.csv
negative_revenue_count = (transactions_df['gross_revenue'] < 0).sum()
print("Số lượng gross_revenue bị âm:", negative_revenue_count)

'quantity': [3 1 2 4]
'discount_applied': [0.   0.15 0.2  0.05 0.1 ]
'refund_flag': [0 1]
Số lượng mỗi loại 'quantity':
quantity
1    77352
2    15327
3     7324
4     3124
Name: count, dtype: int64
Số lượng mỗi loại 'discount_applied':
discount_applied
0.00    61923
0.05    15473
0.10    12370
0.15     8311
0.20     5050
Name: count, dtype: int64
Số lượng mỗi loại 'refund_flag':
refund_flag
0    100098
1      3029
Name: count, dtype: int64
Số lượng gross_revenue bị âm: 2704

In [23]:
#in ra những dòng có refund_flag = 1, sắp xếp theo gross_revenue tăng dần
refund_transactions = transactions_df[transactions_df['refund_flag'] == 1].sort_values(by='gross_revenue')
print("Các giao dịch có refund_flag = 1, sắp xếp theo gross_revenue tăng dần:")
display(refund_transactions)

Các giao dịch có refund_flag = 1, sắp xếp theo gross_revenue tăng dần:

,transaction_id,timestamp,customer_id,product_id,quantity,discount_applied,gross_revenue,campaign_id,refund_flag
39511,39512,2021-05-12 19:08:19,18140,919.0,4,0.0,-783.04,16,1
40841,40842,2021-10-30 02:21:20,3253,128.0,4,0.0,-761.64,31,1
58519,58520,2023-12-11 20:18:54,77943,1960.0,3,0.0,-753.24,25,1
7921,7922,2021-11-01 20:44:49,46325,649.0,4,0.0,-750.12,5,1
20145,20146,2021-07-23 21:20:18,66163,1280.0,4,0.2,-656.58,32,1
...,...,...,...,...,...,...,...,...,...
102058,102059,2022-12-29 06:34:32,14691,NaN,1,0.2,NaN,0,1
102608,102609,2023-03-14 20:31:54,18972,NaN,1,0.1,NaN,3,1
102920,102921,2022-11-06 07:38:36,93381,NaN,4,0.0,NaN,0,1
102968,102969,2023-03-20 06:11:04,63522,NaN,1,0.0,NaN,23,1
103040,103041,2023-04-23 19:30:25,32374,NaN,1,0.2,NaN,26,1

In [33]:
# chuyển tên cột events.timestamp → event_timestamp, transactions.timestamp → transaction_timestamp, transactions.refund_flag → is_refunded
events_df.rename(columns={'timestamp': 'event_timestamp'}, inplace=True)
transactions_df.rename(columns={'timestamp': 'transaction_timestamp', 'refund_flag': 'is_refunded'}, inplace=True)

In [50]:
#liệt kê tên các cột trong các file event, product, transaction
print("Các cột trong events.csv:", events_df.columns.tolist())
print("Các cột trong products.csv:", products_df.columns.tolist())
print("Các cột trong transactions.csv:", transactions_df.columns.tolist())

Các cột trong events.csv: ['event_id', 'event_timestamp', 'customer_id', 'session_id', 'event_type', 'product_id', 'device_type', 'traffic_source', 'campaign_id', 'page_category', 'session_duration_sec', 'experiment_group']
Các cột trong products.csv: ['product_id', 'category', 'brand', 'base_price', 'launch_date', 'is_premium']
Các cột trong transactions.csv: ['transaction_id', 'transaction_timestamp', 'customer_id', 'product_id', 'quantity', 'discount_applied', 'gross_revenue', 'campaign_id', 'is_refunded']

In [42]:
# Chỉ dùng cột parsed để kiểm tra lỗi
invalid_event_timestamps = events_df["event_timestamp_parsed"].isna().sum()
print("Invalid event timestamps:", invalid_event_timestamps)

Invalid event timestamps: 0

In [43]:
# Vì không có lỗi, xóa cột tạm
events_df = events_df.drop(columns=["event_timestamp_parsed"])

In [44]:
# Parse transaction_timestamp để kiểm tra lỗi
transactions_df["transaction_timestamp_parsed"] = pd.to_datetime(
    transactions_df["transaction_timestamp"],
    errors="coerce"
)

# Đếm số dòng lỗi datetime
invalid_transaction_timestamps = transactions_df["transaction_timestamp_parsed"].isna().sum()
print("Invalid transaction timestamps:", invalid_transaction_timestamps)

# Kiểm tra dtype
print(transactions_df[["transaction_timestamp", "transaction_timestamp_parsed"]].dtypes)

Invalid transaction timestamps: 0
transaction_timestamp                      str
transaction_timestamp_parsed    datetime64[us]
dtype: object

In [45]:
transactions_df = transactions_df.drop(columns=["transaction_timestamp_parsed"])

In [49]:
# Parse launch_date để kiểm tra lỗi format
products_df["launch_date_parsed"] = pd.to_datetime(
    products_df["launch_date"],
    errors="coerce"
)

# Đếm số ngày lỗi
invalid_launch_dates = products_df["launch_date_parsed"].isna().sum()
print("Invalid launch dates:", invalid_launch_dates)

# Kiểm tra dtype
print(products_df[["launch_date", "launch_date_parsed"]].dtypes)

# Nếu invalid = 0, xóa cột tạm
products_df = products_df.drop(columns=["launch_date_parsed"])

Invalid launch dates: 0
launch_date                      str
launch_date_parsed    datetime64[us]
dtype: object

In [51]:
print("events_df columns:")
print(events_df.columns.tolist())

print("\nproducts_df columns:")
print(products_df.columns.tolist())

print("\ntransactions_df columns:")
print(transactions_df.columns.tolist())

events_df columns:
['event_id', 'event_timestamp', 'customer_id', 'session_id', 'event_type', 'product_id', 'device_type', 'traffic_source', 'campaign_id', 'page_category', 'session_duration_sec', 'experiment_group']

products_df columns:
['product_id', 'category', 'brand', 'base_price', 'launch_date', 'is_premium']

transactions_df columns:
['transaction_id', 'transaction_timestamp', 'customer_id', 'product_id', 'quantity', 'discount_applied', 'gross_revenue', 'campaign_id', 'is_refunded']

In [52]:
from pathlib import Path

output_dir = Path("data/local_preprocessed")
output_dir.mkdir(parents=True, exist_ok=True)

events_df.to_csv(output_dir / "events.csv", index=False)
products_df.to_csv(output_dir / "products.csv", index=False)
transactions_df.to_csv(output_dir / "transactions.csv", index=False)

print("Export completed:")
print(output_dir / "events.csv")
print(output_dir / "products.csv")
print(output_dir / "transactions.csv")

Export completed:
data\local_preprocessed\events.csv
data\local_preprocessed\products.csv
data\local_preprocessed\transactions.csv

In [54]:
# Kiểm tra lại các file đã xuất
events_check = pd.read_csv(output_dir / "events.csv")
products_check = pd.read_csv(output_dir / "products.csv")
transactions_check = pd.read_csv(output_dir / "transactions.csv")

print(events_check.shape)
print(products_check.shape)
print(transactions_check.shape)

(2000000, 12)
(2000, 6)
(103127, 9)